export interface Game {
  id: string;
  title: string;
  platform: 'Steam' | 'Epic' | 'Riot';
  genre: string;
  coverUrl: string;
  playtime: number;
  lastPlayed: string;
  status: 'playing' | 'completed' | 'wishlist' | 'not_started';
  rating: number;
  description: string;
  achievements: { total: number; unlocked: number };
  size: number;
  releaseYear: number;
}

export interface Friend {
  id: string;
  name: string;
  avatar: string;
  currentGame?: string;
  status: 'online' | 'offline' | 'in-game';
}

export interface Activity {
  id: string;
  type: 'achievement' | 'game_launch' | 'friend_activity';
  text: string;
  timestamp: string;
}

export const mockGames: Game[] = [
  {
    id: "g1",
    title: "Void Protocol",
    platform: "Steam",
    genre: "RPG",
    coverUrl: "https://picsum.photos/seed/g1/400/600",
    playtime: 124.5,
    lastPlayed: "2 hours ago",
    status: "playing",
    rating: 4.8,
    description: "Navigate the silent expanse of space in this narrative-driven RPG. Will you uncover the secrets of the Void Protocol, or become just another ghost in the machine?",
    achievements: { total: 50, unlocked: 23 },
    size: 45.2,
    releaseYear: 2023,
  },
  {
    id: "g2",
    title: "Neon Dynasty",
    platform: "Epic",
    genre: "Action",
    coverUrl: "https://picsum.photos/seed/g2/400/600",
    playtime: 89.0,
    lastPlayed: "Yesterday",
    status: "completed",
    rating: 4.5,
    description: "A cyberpunk action spectacle where you hack, slash, and dash through a neon-drenched metropolis to take down a corrupt megacorporation.",
    achievements: { total: 42, unlocked: 42 },
    size: 65.0,
    releaseYear: 2022,
  },
  {
    id: "g3",
    title: "Crimson Covenant",
    platform: "Steam",
    genre: "Strategy",
    coverUrl: "https://picsum.photos/seed/g3/400/600",
    playtime: 312.0,
    lastPlayed: "3 days ago",
    status: "playing",
    rating: 4.9,
    description: "Lead your vampire clan to dominance in this grand strategy game. Diplomacy, warfare, and blood rituals are your tools.",
    achievements: { total: 100, unlocked: 78 },
    size: 28.4,
    releaseYear: 2024,
  },
  {
    id: "g4",
    title: "Shadow Protocol",
    platform: "Riot",
    genre: "Shooter",
    coverUrl: "https://picsum.photos/seed/g4/400/600",
    playtime: 56.5,
    lastPlayed: "1 week ago",
    status: "playing",
    rating: 4.2,
    description: "Tactical 5v5 hero shooter where shadows are your best friend. Utilize unique abilities to outsmart your opponents.",
    achievements: { total: 0, unlocked: 0 },
    size: 32.1,
    releaseYear: 2023,
  },
  {
    id: "g5",
    title: "Eclipse Rising",
    platform: "Steam",
    genre: "Adventure",
    coverUrl: "https://picsum.photos/seed/g5/400/600",
    playtime: 0,
    lastPlayed: "Never",
    status: "wishlist",
    rating: 0,
    description: "An atmospheric puzzle adventure about bringing light back to a world consumed by an eternal eclipse.",
    achievements: { total: 30, unlocked: 0 },
    size: 15.6,
    releaseYear: 2025,
  },
  {
    id: "g6",
    title: "The Last Bastion",
    platform: "Epic",
    genre: "Survival",
    coverUrl: "https://picsum.photos/seed/g6/400/600",
    playtime: 15.2,
    lastPlayed: "2 weeks ago",
    status: "not_started",
    rating: 3.8,
    description: "Survive against hordes of mutated creatures while managing the resources of humanity's final outpost.",
    achievements: { total: 60, unlocked: 5 },
    size: 40.8,
    releaseYear: 2021,
  },
  {
    id: "g7",
    title: "Phantom Gate",
    platform: "Steam",
    genre: "RPG",
    coverUrl: "https://picsum.photos/seed/g7/400/600",
    playtime: 210.5,
    lastPlayed: "1 month ago",
    status: "completed",
    rating: 4.7,
    description: "Step through the Phantom Gate into a realm of magic and mystery. A classic JRPG experience with modern visuals.",
    achievements: { total: 85, unlocked: 80 },
    size: 55.3,
    releaseYear: 2020,
  },
  {
    id: "g8",
    title: "Cybernetic Drift",
    platform: "Steam",
    genre: "Racing",
    coverUrl: "https://picsum.photos/seed/g8/400/600",
    playtime: 42.0,
    lastPlayed: "5 days ago",
    status: "playing",
    rating: 4.1,
    description: "High-speed futuristic racing with anti-gravity vehicles and intense electronic beats.",
    achievements: { total: 35, unlocked: 12 },
    size: 22.0,
    releaseYear: 2024,
  },
  {
    id: "g9",
    title: "Stellar Horizon",
    platform: "Epic",
    genre: "Strategy",
    coverUrl: "https://picsum.photos/seed/g9/400/600",
    playtime: 0,
    lastPlayed: "Never",
    status: "wishlist",
    rating: 0,
    description: "4X space strategy game. Expand your empire across the galaxy.",
    achievements: { total: 120, unlocked: 0 },
    size: 38.5,
    releaseYear: 2025,
  },
  {
    id: "g10",
    title: "Bloodline Requiem",
    platform: "Steam",
    genre: "Action",
    coverUrl: "https://picsum.photos/seed/g10/400/600",
    playtime: 15.5,
    lastPlayed: "Yesterday",
    status: "playing",
    rating: 4.4,
    description: "A soulslike action game with punishing difficulty and deep lore.",
    achievements: { total: 40, unlocked: 8 },
    size: 48.0,
    releaseYear: 2023,
  },
  {
    id: "g11",
    title: "Aetherial Echoes",
    platform: "Epic",
    genre: "RPG",
    coverUrl: "https://picsum.photos/seed/g11/400/600",
    playtime: 180.2,
    lastPlayed: "2 months ago",
    status: "completed",
    rating: 4.6,
    description: "Explore floating islands and uncover ancient mysteries.",
    achievements: { total: 55, unlocked: 55 },
    size: 34.2,
    releaseYear: 2022,
  },
  {
    id: "g12",
    title: "Iron Vanguard",
    platform: "Steam",
    genre: "Strategy",
    coverUrl: "https://picsum.photos/seed/g12/400/600",
    playtime: 25.0,
    lastPlayed: "3 weeks ago",
    status: "playing",
    rating: 4.0,
    description: "Command a squad of mechs in tactical turn-based combat.",
    achievements: { total: 45, unlocked: 15 },
    size: 18.9,
    releaseYear: 2024,
  },
  {
    id: "g13",
    title: "Apex Legends",
    platform: "Riot",
    genre: "Shooter",
    coverUrl: "https://picsum.photos/seed/g13/400/600",
    playtime: 850.5,
    lastPlayed: "Today",
    status: "playing",
    rating: 4.5,
    description: "Fast-paced battle royale with character abilities.",
    achievements: { total: 0, unlocked: 0 },
    size: 60.0,
    releaseYear: 2019,
  },
  {
    id: "g14",
    title: "Mystic Forge",
    platform: "Steam",
    genre: "Simulation",
    coverUrl: "https://picsum.photos/seed/g14/400/600",
    playtime: 12.4,
    lastPlayed: "6 months ago",
    status: "not_started",
    rating: 3.9,
    description: "Run your own magical blacksmith shop.",
    achievements: { total: 25, unlocked: 2 },
    size: 5.5,
    releaseYear: 2021,
  },
  {
    id: "g15",
    title: "Project Nova",
    platform: "Epic",
    genre: "Adventure",
    coverUrl: "https://picsum.photos/seed/g15/400/600",
    playtime: 0,
    lastPlayed: "Never",
    status: "wishlist",
    rating: 0,
    description: "Unravel a sci-fi conspiracy on a remote planet.",
    achievements: { total: 30, unlocked: 0 },
    size: 28.0,
    releaseYear: 2026,
  },
  {
    id: "g16",
    title: "Gladius",
    platform: "Steam",
    genre: "Action",
    coverUrl: "https://picsum.photos/seed/g16/400/600",
    playtime: 60.5,
    lastPlayed: "1 year ago",
    status: "completed",
    rating: 4.3,
    description: "Brutal arena combat in a fantasy Rome setting.",
    achievements: { total: 40, unlocked: 35 },
    size: 20.1,
    releaseYear: 2018,
  },
  {
    id: "g17",
    title: "Quantum Breach",
    platform: "Steam",
    genre: "RPG",
    coverUrl: "https://picsum.photos/seed/g17/400/600",
    playtime: 4.5,
    lastPlayed: "Yesterday",
    status: "playing",
    rating: 4.8,
    description: "Hack your way through a digital landscape.",
    achievements: { total: 50, unlocked: 5 },
    size: 15.0,
    releaseYear: 2025,
  },
  {
    id: "g18",
    title: "Abyssal Depths",
    platform: "Epic",
    genre: "Survival",
    coverUrl: "https://picsum.photos/seed/g18/400/600",
    playtime: 110.0,
    lastPlayed: "2 days ago",
    status: "playing",
    rating: 4.2,
    description: "Survive at the bottom of the ocean. Watch your oxygen.",
    achievements: { total: 60, unlocked: 40 },
    size: 30.5,
    releaseYear: 2023,
  },
  {
    id: "g19",
    title: "Chronos Shift",
    platform: "Steam",
    genre: "Puzzle",
    coverUrl: "https://picsum.photos/seed/g19/400/600",
    playtime: 8.0,
    lastPlayed: "1 month ago",
    status: "not_started",
    rating: 4.0,
    description: "Time-manipulation puzzles.",
    achievements: { total: 20, unlocked: 5 },
    size: 10.2,
    releaseYear: 2022,
  },
  {
    id: "g20",
    title: "Wasteland Drifter",
    platform: "Steam",
    genre: "RPG",
    coverUrl: "https://picsum.photos/seed/g20/400/600",
    playtime: 0,
    lastPlayed: "Never",
    status: "wishlist",
    rating: 0,
    description: "Post-apocalyptic open world RPG.",
    achievements: { total: 80, unlocked: 0 },
    size: 70.0,
    releaseYear: 2026,
  }
];

export const mockFriends: Friend[] = [
  { id: "f1", name: "CyberNinja", avatar: "CN", status: "in-game", currentGame: "Void Protocol" },
  { id: "f2", name: "GlitchQueen", avatar: "GQ", status: "online" },
  { id: "f3", name: "PixelPaladin", avatar: "PP", status: "offline" },
  { id: "f4", name: "VoidWalker", avatar: "VW", status: "in-game", currentGame: "Crimson Covenant" },
];

export const mockActivity: Activity[] = [
  { id: "a1", type: "achievement", text: "Unlocked 'Master of the Void' in Void Protocol", timestamp: "10 mins ago" },
  { id: "a2", type: "friend_activity", text: "CyberNinja started playing Void Protocol", timestamp: "2 hours ago" },
  { id: "a3", type: "game_launch", text: "You played Neon Dynasty", timestamp: "Yesterday" },
  { id: "a4", type: "achievement", text: "Unlocked 'First Blood' in Crimson Covenant", timestamp: "3 days ago" },
];

export const mockWeeklyPlaytime = [
  { day: "Mon", hours: 2.5 },
  { day: "Tue", hours: 1.8 },
  { day: "Wed", hours: 4.2 },
  { day: "Thu", hours: 3.0 },
  { day: "Fri", hours: 5.5 },
  { day: "Sat", hours: 8.0 },
  { day: "Sun", hours: 6.5 },
];
